# Generated by Django 5.1.7 on 2025-03-28 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(default='default_field', help_text='Name of the field', max_length=100)),
                ('module_id', models.CharField(help_text="Model identifier (e.g., 'users.User')", max_length=50)),
                ('field_type', models.CharField(default='CharField', help_text='Type of the field', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['module_id', 'field_name'],
                'unique_together': {('module_id', 'field_name')},
            },
        ),
    ]
