# Generated by Django 5.1.7 on 2025-03-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Operation Name')),
                ('transfer_type', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=10, verbose_name='Transfer Type')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=10, verbose_name='File Type')),
                ('source_model', models.CharField(max_length=255, verbose_name='Source Model')),
                ('file_path', models.FileField(upload_to='data_transfers/', verbose_name='File Path')),
                ('field_mapping', models.JSONField(blank=True, null=True, verbose_name='Field Mapping')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Records Processed')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Records Failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Data Transfer',
                'verbose_name_plural': 'Data Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
