# Generated by Django 5.1.7 on 2025-03-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_transfer', '0002_datatransfermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datatransfermodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
