# Generated by Django 4.2.11 on 2025-04-10 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_templates', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_templates_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='groups', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_groups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_groups_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entity.department'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entity.team'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contacttemplate',
            unique_together={('name', 'organization')},
        ),
    ]
