# Generated by Django 4.2.11 on 2025-04-23 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_templates', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contacttemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactsegment',
            name='contact_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='contacts.contactlist'),
        ),
        migrations.AddField(
            model_name='contactsegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactsegment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactsegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactnotenotification',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contacts.contactnote'),
        ),
        migrations.AddField(
            model_name='contactnotenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactnotemonitoring',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='contacts.contactnote'),
        ),
        migrations.AddField(
            model_name='contactnotemonitoring',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_monitoring_records', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactnotemonitoring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_notes', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactmonitoring',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactmonitoring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmonitoring',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactmonitoring',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmonitoring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmetrics',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactmetrics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmetrics',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactmetrics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactlisttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactlisttemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_list_templates', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactlisttemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='contacts.contactlisttemplate'),
        ),
        migrations.AddField(
            model_name='contactlisttemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='lists', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgrouptemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgrouptemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_templates', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactgrouptemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='contacts.contactgrouptemplate'),
        ),
        migrations.AddField(
            model_name='contactgrouptemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroupmonitoring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroupmonitoring',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='contacts.contactgroup'),
        ),
        migrations.AddField(
            model_name='contactgroupmonitoring',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactgroupmonitoring',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroupmonitoring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='groups', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contacts.contactgroup'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entity.department'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entity.team'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationmonitoring',
            name='communication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='contacts.communication'),
        ),
        migrations.AddField(
            model_name='communicationmonitoring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationmonitoring',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='communicationmonitoring',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationmonitoring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='communication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='communication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contacttemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='contactsegment',
            unique_together={('name', 'contact_list')},
        ),
        migrations.AddIndex(
            model_name='contactnotenotification',
            index=models.Index(fields=['user', '-created_at'], name='contacts_co_user_id_4056d3_idx'),
        ),
        migrations.AddIndex(
            model_name='contactnotenotification',
            index=models.Index(fields=['note', '-created_at'], name='contacts_co_note_id_14ca74_idx'),
        ),
        migrations.AddIndex(
            model_name='contactnotenotification',
            index=models.Index(fields=['notification_type', '-created_at'], name='contacts_co_notific_d7c636_idx'),
        ),
        migrations.AddIndex(
            model_name='contactnotemonitoring',
            index=models.Index(fields=['note', '-created_at'], name='contacts_co_note_id_72accd_idx'),
        ),
        migrations.AddIndex(
            model_name='contactnotemonitoring',
            index=models.Index(fields=['user', '-created_at'], name='contacts_co_user_id_ced9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactnotemonitoring',
            index=models.Index(fields=['organization', '-created_at'], name='contacts_co_organiz_2f2db6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactnotemonitoring',
            index=models.Index(fields=['activity_type', '-created_at'], name='contacts_co_activit_5a08f5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmonitoring',
            index=models.Index(fields=['contact', 'activity_type'], name='contacts_co_contact_4128fa_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmonitoring',
            index=models.Index(fields=['user', 'activity_type'], name='contacts_co_user_id_785f70_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmonitoring',
            index=models.Index(fields=['organization', 'activity_type'], name='contacts_co_organiz_fa4928_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmetrics',
            index=models.Index(fields=['contact'], name='contacts_co_contact_e1650d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmetrics',
            index=models.Index(fields=['organization'], name='contacts_co_organiz_3a92dc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmetrics',
            index=models.Index(fields=['engagement_score'], name='contacts_co_engagem_244f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmetrics',
            index=models.Index(fields=['last_interaction'], name='contacts_co_last_in_4865d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactlisttemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='contactlist',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='contactgrouptemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='contactgroupmonitoring',
            index=models.Index(fields=['group', 'activity_type'], name='contacts_co_group_i_943949_idx'),
        ),
        migrations.AddIndex(
            model_name='contactgroupmonitoring',
            index=models.Index(fields=['user', 'activity_type'], name='contacts_co_user_id_e805cb_idx'),
        ),
        migrations.AddIndex(
            model_name='contactgroupmonitoring',
            index=models.Index(fields=['organization', 'activity_type'], name='contacts_co_organiz_1102cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationtemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['communication'], name='contacts_co_communi_d1f672_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['user'], name='contacts_co_user_id_a02f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['activity_type'], name='contacts_co_activit_b07792_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['organization'], name='contacts_co_organiz_0ddaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['created_at'], name='contacts_co_created_d3c889_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['contact'], name='contacts_co_contact_cd7366_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['organization'], name='contacts_co_organiz_cbe5af_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status'], name='contacts_co_status_345253_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['communication_type'], name='contacts_co_communi_f3bd51_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['scheduled_at'], name='contacts_co_schedul_7b630a_idx'),
        ),
    ]
