# Generated by Django 5.1.7 on 2025-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_created_by_alter_contact_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
