# Generated by Django 4.2.11 on 2025-04-13 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0002_initial'),
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('email', 'Email'), ('call', 'Call'), ('export', 'Export'), ('import', 'Import'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='contacts.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_monitoring_records', to='entity.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Activity Record',
                'verbose_name_plural': 'Contact Activity Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact'], name='contacts_co_contact_91e9b6_idx'), models.Index(fields=['organization'], name='contacts_co_organiz_db7caa_idx'), models.Index(fields=['activity_type'], name='contacts_co_activit_e95e39_idx'), models.Index(fields=['created_at'], name='contacts_co_created_911d7c_idx')],
            },
        ),
    ]
