# Generated by Django 4.2.11 on 2025-04-13 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0002_initial'),
        ('contacts', '0003_contactmonitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Call'), ('letter', 'Letter'), ('meeting', 'Meeting'), ('other', 'Other')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('send', 'Send'), ('schedule', 'Schedule'), ('cancel', 'Cancel'), ('open', 'Open'), ('click', 'Click'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Communication Activity Record',
                'verbose_name_plural': 'Communication Activity Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Call'), ('letter', 'Letter'), ('meeting', 'Meeting'), ('other', 'Other')], default='email', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Communication Template',
                'verbose_name_plural': 'Communication Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroupMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('add_contact', 'Add Contact'), ('remove_contact', 'Remove Contact'), ('export', 'Export'), ('import', 'Import'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Contact Group Activity Record',
                'verbose_name_plural': 'Contact Group Activity Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('fields', models.JSONField(help_text='JSON structure defining the template fields and their properties')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Contact Group Template',
                'verbose_name_plural': 'Contact Group Templates',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='contactmonitoring',
            name='contacts_co_contact_91e9b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmonitoring',
            name='contacts_co_organiz_db7caa_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmonitoring',
            name='contacts_co_activit_e95e39_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmonitoring',
            name='contacts_co_created_911d7c_idx',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contacts.contactgroup'),
        ),
        migrations.AddIndex(
            model_name='contactmonitoring',
            index=models.Index(fields=['contact', 'activity_type'], name='contacts_co_contact_4128fa_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmonitoring',
            index=models.Index(fields=['user', 'activity_type'], name='contacts_co_user_id_785f70_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmonitoring',
            index=models.Index(fields=['organization', 'activity_type'], name='contacts_co_organiz_fa4928_idx'),
        ),
        migrations.AddField(
            model_name='contactgrouptemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgrouptemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_templates', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactgrouptemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='contacts.contactgrouptemplate'),
        ),
        migrations.AddField(
            model_name='contactgrouptemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_templates_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactgroupmonitoring',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='contacts.contactgroup'),
        ),
        migrations.AddField(
            model_name='contactgroupmonitoring',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_monitoring_records', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='contactgroupmonitoring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_templates_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationmonitoring',
            name='communication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='contacts.communication'),
        ),
        migrations.AddField(
            model_name='communicationmonitoring',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_monitoring_records', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='communicationmonitoring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='communication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='communication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contactgrouptemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='contactgroupmonitoring',
            index=models.Index(fields=['group', 'activity_type'], name='contacts_co_group_i_943949_idx'),
        ),
        migrations.AddIndex(
            model_name='contactgroupmonitoring',
            index=models.Index(fields=['user', 'activity_type'], name='contacts_co_user_id_e805cb_idx'),
        ),
        migrations.AddIndex(
            model_name='contactgroupmonitoring',
            index=models.Index(fields=['organization', 'activity_type'], name='contacts_co_organiz_1102cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationtemplate',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['communication'], name='contacts_co_communi_d1f672_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['user'], name='contacts_co_user_id_a02f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['activity_type'], name='contacts_co_activit_b07792_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['organization'], name='contacts_co_organiz_0ddaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmonitoring',
            index=models.Index(fields=['created_at'], name='contacts_co_created_d3c889_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['contact'], name='contacts_co_contact_cd7366_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['organization'], name='contacts_co_organiz_cbe5af_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status'], name='contacts_co_status_345253_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['communication_type'], name='contacts_co_communi_f3bd51_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['scheduled_at'], name='contacts_co_schedul_7b630a_idx'),
        ),
    ]
