# Generated by Django 4.2.11 on 2025-04-13 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0005_contactlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('filter_criteria', models.JSONField(help_text='JSON structure defining the filter criteria for the segment')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='contacts.contactlist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_segments_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_segments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Segment',
                'verbose_name_plural': 'Contact Segments',
                'ordering': ['name'],
                'unique_together': {('name', 'contact_list')},
            },
        ),
    ]
