# Generated by Django 4.2.11 on 2025-04-14 15:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0002_initial'),
        ('contacts', '0009_communication_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('engagement_score', models.FloatField(default=0.0, help_text='Overall engagement score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('last_interaction', models.DateTimeField(blank=True, help_text='Timestamp of last interaction', null=True)),
                ('total_interactions', models.PositiveIntegerField(default=0, help_text='Total number of interactions')),
                ('email_opens', models.PositiveIntegerField(default=0, help_text='Number of email opens')),
                ('email_clicks', models.PositiveIntegerField(default=0, help_text='Number of email link clicks')),
                ('response_rate', models.FloatField(default=0.0, help_text='Response rate percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('average_response_time', models.DurationField(blank=True, help_text='Average time to respond', null=True)),
                ('communication_frequency', models.FloatField(default=0.0, help_text='Average number of communications per week')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='entity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Metrics',
                'verbose_name_plural': 'Contact Metrics',
                'indexes': [models.Index(fields=['contact'], name='contacts_co_contact_e1650d_idx'), models.Index(fields=['organization'], name='contacts_co_organiz_3a92dc_idx'), models.Index(fields=['engagement_score'], name='contacts_co_engagem_244f5e_idx'), models.Index(fields=['last_interaction'], name='contacts_co_last_in_4865d1_idx')],
            },
        ),
    ]
