# Generated by Django 4.2.11 on 2025-04-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0010_contactmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='contact_notes/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_notes', to='entity.organization')),
            ],
            options={
                'verbose_name': 'Contact Note',
                'verbose_name_plural': 'Contact Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactNoteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('mention', 'Mention'), ('comment', 'Comment'), ('attachment', 'Attachment'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contacts.contactnote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note Notification',
                'verbose_name_plural': 'Note Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='contacts_co_user_id_4056d3_idx'), models.Index(fields=['note', '-created_at'], name='contacts_co_note_id_14ca74_idx'), models.Index(fields=['notification_type', '-created_at'], name='contacts_co_notific_d7c636_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactNoteMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('attachment_add', 'Add Attachment'), ('attachment_remove', 'Remove Attachment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='contacts.contactnote')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_monitoring_records', to='entity.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note Activity Record',
                'verbose_name_plural': 'Note Activity Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['note', '-created_at'], name='contacts_co_note_id_72accd_idx'), models.Index(fields=['user', '-created_at'], name='contacts_co_user_id_ced9d1_idx'), models.Index(fields=['organization', '-created_at'], name='contacts_co_organiz_2f2db6_idx'), models.Index(fields=['activity_type', '-created_at'], name='contacts_co_activit_5a08f5_idx')],
            },
        ),
    ]
