# Generated by Django 4.2.11 on 2025-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contactnote_contactnotenotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
