# Generated by Django 4.2.11 on 2025-04-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_initial'),
        ('rbac', '0006_audit_retention_period'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(help_text='Roles assigned to this user.', related_name='assigned_users', through='rbac.UserRole', to='rbac.role'),
        ),
    ]
