# Generated by Django 5.1.7 on 2025-04-04 09:19

import Apps.core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('action_type', models.CharField(choices=[('email', 'Send Email'), ('notification', 'Send Notification'), ('webhook', 'Call Webhook'), ('task', 'Create Task')], max_length=20, verbose_name='Action Type')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-created_at'],
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Task Status')),
                ('task_result', models.JSONField(blank=True, null=True, verbose_name='Task Result')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('trigger_type', models.CharField(choices=[('time', 'Time-based'), ('event', 'Event-based'), ('data', 'Data-based')], max_length=20, verbose_name='Trigger Type')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='automation.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
                'ordering': ['-created_at'],
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='automation.action', verbose_name='Action')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='automation.trigger', verbose_name='Trigger')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='automation.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['-created_at'],
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('node_type', models.CharField(choices=[('trigger', 'Trigger'), ('action', 'Action'), ('condition', 'Condition'), ('delay', 'Delay')], max_length=20, verbose_name='Node Type')),
                ('configuration', models.JSONField(default=dict, verbose_name='Configuration')),
                ('position_x', models.FloatField(default=0, verbose_name='X Position')),
                ('position_y', models.FloatField(default=0, verbose_name='Y Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='automation.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'ordering': ['workflow', 'created_at'],
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('configuration', models.JSONField(default=dict, verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='automation.node', verbose_name='Source Node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='automation.node', verbose_name='Target Node')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='automation.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
                'ordering': ['workflow', 'created_at'],
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.AddField(
            model_name='action',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.workflow', verbose_name='Workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('configuration', models.JSONField(default=dict, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'ordering': ['-created_at'],
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['name'], name='automation__name_0442ef_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['is_active'], name='automation__is_acti_ac172e_idx'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['name'], name='automation__name_1f11c7_idx'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['trigger_type'], name='automation__trigger_d1ea29_idx'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['is_active'], name='automation__is_acti_0211bd_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['name'], name='automation__name_0b4d09_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['is_active'], name='automation__is_acti_e15132_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['name'], name='automation__name_7cd74f_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type'], name='automation__node_ty_38eaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['workflow'], name='automation__workflo_6f7cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['is_active'], name='automation__is_acti_e2b418_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['workflow'], name='automation__workflo_757f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['source_node'], name='automation__source__fea411_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['target_node'], name='automation__target__381b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['is_active'], name='automation__is_acti_ab8c06_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['name'], name='automation__name_26577f_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['action_type'], name='automation__action__2246a3_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['is_active'], name='automation__is_acti_f437d2_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['name'], name='automation__name_ca46b6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['is_active'], name='automation__is_acti_5bdcca_idx'),
        ),
    ]
