# Generated by Django 5.1.7 on 2025-04-04 10:25

import Apps.core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20, verbose_name='Status')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Execution Time (seconds)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Trigger Execution',
                'verbose_name_plural': 'Trigger Executions',
                'ordering': ['-started_at'],
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TriggerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_executions', models.IntegerField(default=0, verbose_name='Total Executions')),
                ('successful_executions', models.IntegerField(default=0, verbose_name='Successful Executions')),
                ('failed_executions', models.IntegerField(default=0, verbose_name='Failed Executions')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='Success Rate (%)')),
                ('average_execution_time', models.FloatField(default=0.0, verbose_name='Average Execution Time (seconds)')),
                ('last_execution_status', models.CharField(max_length=20, null=True, verbose_name='Last Execution Status')),
                ('last_execution_time', models.DateTimeField(null=True, verbose_name='Last Execution Time')),
            ],
            options={
                'verbose_name': 'Trigger Metrics',
                'verbose_name_plural': 'Trigger Metrics',
            },
            bases=(Apps.core.mixins.ImportExportMixin, models.Model),
        ),
        migrations.RemoveIndex(
            model_name='connection',
            name='automation__workflo_757f9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='connection',
            name='automation__source__fea411_idx',
        ),
        migrations.RemoveIndex(
            model_name='connection',
            name='automation__target__381b0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='connection',
            name='automation__is_acti_ab8c06_idx',
        ),
        migrations.RemoveIndex(
            model_name='node',
            name='automation__name_7cd74f_idx',
        ),
        migrations.RemoveIndex(
            model_name='node',
            name='automation__node_ty_38eaf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='node',
            name='automation__workflo_6f7cc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='node',
            name='automation__is_acti_e2b418_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowtemplate',
            name='automation__name_ca46b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowtemplate',
            name='automation__is_acti_5bdcca_idx',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='task_result',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='node',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='node',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='node',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='node',
            name='task_result',
        ),
        migrations.RemoveField(
            model_name='node',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='node',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='task_result',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='connection',
            name='configuration',
            field=models.JSONField(verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_connections', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='node',
            name='configuration',
            field=models.JSONField(verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_nodes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('action', 'Action'), ('condition', 'Condition')], max_length=20, verbose_name='Node Type'),
        ),
        migrations.AlterField(
            model_name='node',
            name='position_x',
            field=models.IntegerField(default=0, verbose_name='Position X'),
        ),
        migrations.AlterField(
            model_name='node',
            name='position_y',
            field=models.IntegerField(default=0, verbose_name='Position Y'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='configuration',
            field=models.JSONField(verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='triggerexecution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggerexecution',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.trigger', verbose_name='Trigger'),
        ),
        migrations.AddField(
            model_name='triggerexecution',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggermetrics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggermetrics',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='automation.trigger', verbose_name='Trigger'),
        ),
        migrations.AddField(
            model_name='triggermetrics',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='triggerexecution',
            index=models.Index(fields=['trigger', 'status'], name='automation__trigger_e8cad2_idx'),
        ),
        migrations.AddIndex(
            model_name='triggerexecution',
            index=models.Index(fields=['started_at'], name='automation__started_135387_idx'),
        ),
        migrations.AddIndex(
            model_name='triggerexecution',
            index=models.Index(fields=['status'], name='automation__status_a1a666_idx'),
        ),
        migrations.AddIndex(
            model_name='triggermetrics',
            index=models.Index(fields=['trigger'], name='automation__trigger_72d529_idx'),
        ),
        migrations.AddIndex(
            model_name='triggermetrics',
            index=models.Index(fields=['success_rate'], name='automation__success_2cbb04_idx'),
        ),
        migrations.AddIndex(
            model_name='triggermetrics',
            index=models.Index(fields=['last_execution_time'], name='automation__last_ex_f783fc_idx'),
        ),
    ]
