# Generated by Django 4.2.11 on 2025-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
