# Generated by Django 5.1.7 on 2025-04-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generation_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Generation Time (seconds)'),
        ),
    ]
