# Generated by Django 5.1.7 on 2025-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_report_generation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('generating', 'GENERATING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Task Status'),
        ),
    ]
