# Generated by Django 4.1 on 2023-06-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='discussion_enabled',
            field=models.BooleanField(default=True, help_text='Whether discussions are enabled for this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='discussion_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Settings for project discussions'),
        ),
    ] 