# Generated by Django 4.2.11 on 2025-04-10 06:52

import Apps.data_import_export.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_import_export', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_test_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importexportlog',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import_export.importexportconfig'),
        ),
        migrations.AddField(
            model_name='importexportlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importexportconfig',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=Apps.data_import_export.models.get_content_type_choices, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='importexportconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_import_export_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importexportconfig',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_import_export_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='importexportlog',
            index=models.Index(fields=['-created_at'], name='data_import_created_9fb6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='importexportlog',
            index=models.Index(fields=['performed_by'], name='data_import_perform_ab5871_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importexportconfig',
            unique_together={('name', 'content_type')},
        ),
    ]
