# Generated by Django 4.2.11 on 2025-04-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtering', '0002_test_grouping_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestGroupingModel',
        ),
    ]
