# Generated by Django 5.0.3 on 2025-03-29 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='time_management.timecategory'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
