# Generated by Django 5.0.3 on 2025-03-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0002_timesheetentry_category_timesheetentry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='name',
            field=models.CharField(default='Default Schedule', max_length=100),
        ),
    ]
