# Generated by Django 5.1.7 on 2025-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio/')),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('sample_rate', models.IntegerField(help_text='Sample rate in Hz')),
                ('channels', models.IntegerField(help_text='Number of audio channels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
