# Generated by Django 5.1.7 on 2025-04-02 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the object is active.', verbose_name='active')),
                ('field_name', models.CharField(max_length=255)),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['content_type', 'field_name'],
                'unique_together': {('content_type', 'field_name', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='RBACPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the object is active.', verbose_name='active')),
                ('codename', models.CharField(help_text='Permission codename.', max_length=100, verbose_name='codename')),
                ('name', models.CharField(help_text='Permission name.', max_length=255, verbose_name='name')),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('view', 'View'), ('change', 'Change'), ('add', 'Add')], help_text='Permission type.', max_length=50)),
                ('field_name', models.CharField(blank=True, help_text='Field name this permission applies to.', max_length=100, null=True)),
                ('content_type', models.ForeignKey(help_text='Content type this permission applies to.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['content_type__app_label', 'content_type__model', 'codename'],
                'unique_together': {('content_type', 'codename')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the object is active.', verbose_name='active')),
                ('name', models.CharField(help_text='Name of the role.', max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of the role.', verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent role for inheritance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rbac.role')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the object is active.', verbose_name='active')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('secret_key', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Document',
                'verbose_name_plural': 'Test Documents',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the object is active.', verbose_name='active')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='When this role assignment expires.', null=True, verbose_name='expiry date')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role assigned to the user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User this role is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
                'ordering': ['user__username', 'role__name'],
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(help_text='Users assigned to this role.', related_name='assigned_roles', through='rbac.UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the object is active.', verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('field_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.fieldpermission')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.rbacpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the object.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'role permission',
                'verbose_name_plural': 'role permissions',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'field_permission'), ('role', 'permission')},
            },
        ),
    ]
