# Generated by Django 4.2.11 on 2025-04-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_initial'),
        ('rbac', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.FloatField()),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('summary', 'Summary')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='entity.organization')),
                ('organization_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='rbac.organizationcontext')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization_context', 'metric_name'], name='rbac_organi_organiz_3568cb_idx'), models.Index(fields=['organization_context', 'metric_type'], name='rbac_organi_organiz_db3942_idx'), models.Index(fields=['organization_context', 'timestamp'], name='rbac_organi_organiz_265547_idx')],
            },
        ),
    ]
