# Generated by Django 4.2.11 on 2025-04-12 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_organizationmonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmonitor',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
