# Generated by Django 4.2.11 on 2025-04-12 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0004_alter_organizationmonitor_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.IntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='success', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='organizationmonitor',
            name='rbac_organi_organiz_3568cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationmonitor',
            name='rbac_organi_organiz_db3942_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationmonitor',
            name='rbac_organi_organiz_265547_idx',
        ),
        migrations.AddIndex(
            model_name='organizationmonitor',
            index=models.Index(fields=['organization_context', 'metric_name', 'timestamp'], name='rbac_organi_organiz_1e1f13_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmonitor',
            index=models.Index(fields=['organization_context', 'metric_type', 'timestamp'], name='rbac_organi_organiz_3d54f9_idx'),
        ),
        migrations.AddField(
            model_name='audit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='entity.organization'),
        ),
        migrations.AddField(
            model_name='audit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'action', 'timestamp'], name='rbac_audit_organiz_9c7ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'resource_type', 'timestamp'], name='rbac_audit_organiz_257eea_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'user', 'timestamp'], name='rbac_audit_organiz_fe764e_idx'),
        ),
    ]
