# Generated by Django 4.2.11 on 2025-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_audit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='retention_period',
            field=models.IntegerField(default=365, help_text='Number of days to retain this audit log'),
        ),
    ]
